spring.application.name=order-service
server.port=8081

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/order_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root2022}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# OpenFeign Configuration
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=full

# Resilience4j Global Settings
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.metrics.enabled=true
resilience4j.retry.metrics.enabled=true
resilience4j.bulkhead.metrics.enabled=true
resilience4j.timelimiter.metrics.enabled=true

# Circuit Breaker - Order -> User & Notification
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.notificationService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notificationService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.notificationService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.notificationService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.notificationService.permittedNumberOfCallsInHalfOpenState=3

# Retry
resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=2s
resilience4j.retry.instances.userService.enableExponentialBackoff=true
resilience4j.retry.instances.userService.retryExceptions=com.chella.orderservice.exception.RetryableException,java.io.IOException
resilience4j.retry.instances.userService.ignoreExceptions=com.chella.orderservice.exception.NonRetryableException

resilience4j.retry.instances.notificationService.maxAttempts=3
resilience4j.retry.instances.notificationService.waitDuration=2s
resilience4j.retry.instances.notificationService.enableExponentialBackoff=true
resilience4j.retry.instances.notificationService.retryExceptions=com.chella.orderservice.exception.RetryableException,java.io.IOException
resilience4j.retry.instances.notificationService.ignoreExceptions=com.chella.orderservice.exception.NonRetryableException

# Bulkhead
resilience4j.bulkhead.instances.userService.maxConcurrentCalls=20
resilience4j.bulkhead.instances.userService.maxWaitDuration=1s

resilience4j.bulkhead.instances.notificationService.maxConcurrentCalls=20
resilience4j.bulkhead.instances.notificationService.maxWaitDuration=1s

# TimeLimiter (Timeout)
resilience4j.timelimiter.instances.userService.timeoutDuration=3s
resilience4j.timelimiter.instances.notificationService.timeoutDuration=3s

# Observability (Actuator, Prometheus, Info)
management.endpoints.web.exposure.include=health,info,metrics,prometheus,env,loggers
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.metrics.export.prometheus.enabled=true

info.app.name=${spring.application.name}
info.app.description=Order Service for Microservices
info.app.version=1.0.0


# Distributed Tracing Config
management.tracing.sampling.probability=1.0

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

